name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: rust:bookworm

    steps:
      - uses: actions/checkout@v4

      - name: Run CI
        run: bash ci.sh
